apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget
  namespace: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      containers:
        - name: budget
          image: index.docker.io/spencermehta/budget:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: regcred
