on:
    push:
      branches:
          - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@main

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./deployment/Dockerfile
                  push: true
                  tags: spencermehta/budget:latest

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@main

            - name: Set the Kubernetes context
              uses: azure/k8s-set-context@v2
              with:
                  method: service-account
                  k8s-url: ${{ secrets.KUBERNETES_URL }}
                  k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

            - name: Deploy to the Kubernetes cluster
              uses: azure/k8s-deploy@v1
              with:
                  namespace: budget
                  manifests: |
                      deployment/namespace.yml
                      deployment/service.yml
                      deployment/deployment.yml
                  images: |
                      docker.io/spencermehta/budget:${{ github.sha }}
